Life: arrays.h File Reference
arrays.h File Reference
Functions
int ** arrays (int x, int y)
int read_file (int **A, char *file, int row)
int print_array (int **A, int columns, int rows)
int compare_array (int **A, int **B, int columns, int rows)
Function Documentation
int** arrays (int r, int c)
creates an array and initializes all values as zero
Parameters
r Number of rows in array
c Number of Columns in array
Returns
B The created array
References B.
Referenced by run_life().
int compare_array (int ** A, int ** B, int nrows, int ncolumns)
prints out the given array
Parameters
A The first array
B The second array
columns Size of columns given by the user
rows Size of rows given by the user
Returns
same Returns 0 if they are different and 1 if they are the same
prints out the given array
Parameters
A The first array
B The second array
nrows Number of rows given by the user
ncolumns Number of columns given by the user
Returns
same Returns 0 if they are different and 1 if they are the same
Referenced by run_life().
int print_array (int ** A, int nrows, int ncolumns)
prints out the given array
Parameters
A The array
columns Size of columns given by the user
rows Size of rows given by the user
Returns
0
prints out the given array
Parameters
A The array
nrows Number of rows given by the user
ncolumns Number of columns given by the user
Returns
0
Referenced by run_life().
int read_file (int ** A, char * file, int row)
reads the file with the pattern and puts the pattern into the given array
Parameters
A The array
file The location of the file
row Number of rows given by the user
Returns
1
reads the file with the pattern and puts the pattern into the given array
Parameters
A The array
file The location of the file
row Size of rows given by the user
Returns
1
Referenced by run_life().