Life: run.h File Reference
run.h File Reference
Functions
int run_life (int rows, int columns, int gen, char *file, char pr, char pa)
int neighbors (int r, int c, int **A, int columns, int rows)
int algorithm (int **A, int rows, int columns, int **B, char pr)
Function Documentation
int algorithm (int ** A, int rows, int columns, int ** B, char pr)
creates the new generation a condition of termination is met
Parameters
A The current generation
rows Rows in the grid
columns Columns in the grid
pr Value for printing generations
Returns
0
References columns, neighbors(), and rows.
Referenced by run_life().
int neighbors (int a, int d, int ** A, int columns, int rows)
copies the pattern from the file into an array, prints each generation until a condition of termination is met
Parameters
r row of current cell's location
column of current cell's location
A current array
rows Rows in the grid
columns Columns in the grid
Returns
neighbors Number of neighbors for given cell
calculates number of neighbors for given cell a condition of termination is met
Parameters
a across placement of current cell's location
d down of current cell's location
A current array
rows Rows in the grid
columns Columns in the grid
Returns
neighbors Number of neighbors for given cell
References neighbors().
Referenced by algorithm(), and neighbors().
int run_life (int ncolumns, int nrows, int gen, char * file, char pr, char pa)
copies the pattern from the file into an array, prints each generation until a condition of termination is met
Parameters
rows Rows in the grid
columns Columns in the grid
gen Generations given by user
file Name of file with pattern
pr Value for printing generations
pa Value for pausing generations
Returns
0
References algorithm(), arrays(), B, C, compare_array(), print_array(), and read_file().